=== mil-oss/fgsms/fgsms-server/fgsms.Services/src/main/webapp/admin/quartz-status.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--W3C Schema generated by XMLSpy v2009 sp1 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="volatile" type="xs:boolean"/>
	<xs:element name="version" type="xs:string">

	</xs:element>
	<xs:element name="triggers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="triggerGroup" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="triggerGroup">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="trigger" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string">

			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="trigger">
		<xs:complexType>
			<xs:attribute name="name" use="required" type="xs:string">

			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="stateful" type="xs:boolean"/>
	<xs:element name="scheduler-name" type="xs:string">

	</xs:element>
	<xs:element name="scheduler-instance-id" type="xs:string">

	</xs:element>
	<xs:element name="runningsince" type="xs:dateTime">
	</xs:element>
	<xs:element name="quartz-status">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="scheduler-name"/>
				<xs:element ref="scheduler-instance-id"/>
				<xs:element ref="version"/>
				<xs:element ref="jobs-executed"/>
				<xs:element ref="runningsince"/>
				<xs:element ref="group-names"/>
				<xs:element ref="jobs"/>
				<xs:element ref="triggers"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="jobs-executed" type="xs:long">
	</xs:element>
	<xs:element name="jobs">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="job" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="job">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="durable"/>
				<xs:element ref="stateful"/>
				<xs:element ref="volatile"/>
			</xs:sequence>
			<xs:attribute name="name" use="required" type="xs:string">
			</xs:attribute>
			<xs:attribute name="group" use="required" type="xs:string">
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="group-names">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="group" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="group">
		<xs:complexType>
			<xs:attribute name="name" use="required" type="xs:string">
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="durable" type="xs:boolean"/>
</xs:schema>

=== mil-oss/fgsms/fgsms-server/fgsms.Services/src/main/webapp/admin/example.xml
<?xml version="1.0" encoding="UTF-8"?>
<quartz-status xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="C:\Projects\FGSMS\FGSMS.AuxServices\web\admin\quartz-status.xsd">
	<scheduler-name>Quartz</scheduler-name>
	<scheduler-instance-id>quartz</scheduler-instance-id>
	<version>1.8.6</version>
	<jobs-executed>1231231</jobs-executed>
	<runningsince>2001-12-17T09:30:47Z</runningsince>
	<group-names>
		<group name="FGSMS"/>
		<group name="FGSMS2"/>
	</group-names>
	<jobs>
		<job name="jobname" group="mygroup">
			<durable>true</durable>
			<stateful>false</stateful>
			<volatile>true</volatile>
		</job>
		<job name="jobname2" group="mygroup2">
			<durable>true</durable>
			<stateful>false</stateful>
			<volatile>true</volatile>
		</job>
	</jobs>
	<triggers>
		<triggerGroup name="trigger1group">
			<trigger name="trigger1"/>
			<trigger name="trigger2"/>
		</triggerGroup>
	</triggers>
</quartz-status>
